blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'welcome/index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :articles do
    put :favorite, on: :member
   
  end
  
  resources :articles do  #create a route for the comments model
    resources :comments
    resources :likes
    resources :dislikes
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/article.rb
class Article < ApplicationRecord
    # User class has_many articles, so we need to update the association in this Article class
    belongs_to :user
    
    # This Class is associated with Comments class in a "has_many" relationship
    # dependent option of an association used to delete all comments when deleting article
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :dislikes, dependent: :destroy
    has_many :favorite_articles 
    has_many :favorited_by, through: :favorite_articles, source: :user
    
   
    # Adds the ability to display all comments asociated with an Article
    # using @article.comments
    validates :title, presence: true, length: {minimum: 5}
    validates :text, presence: true, length: {minimum: 10}
    
     def self.search(search)
     
    where (['title LIKE ?', "%#{search}%"])
    
     end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all.order(:created_at).reverse
            if params[:order] == 'created_at DESC'
                @articles = Article.all.order('created_at DESC')
            elsif params[:order] == 'title'
                @articles = Article.all.order('title')
            elsif params[:order] == 'created_at ASC'
                @articles = Article.all.order('created_at ASC')
            else
                @articles = Article.all.reverse
            end
            
        if params[:search]
        @articles = Article.search(params[:search])
        end
    end
    
    def show
        @article = Article.find(params[:id])
       
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        # add current user in this controller for creating new articles
        @article.user = current_user
        
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    
    def edit
        @article=Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        
        redirect_to articles_path
    end
    
     def favorite
        @article = Article.find params[:id]
        type = params[:type]
        
        if type == "favorite"
            current_user.favorites << @article
            redirect_back fallback_location: @article, notice: "You favorited #{@article.title}"
            
        elsif type == "unfavorite"
             current_user.favorites.delete(@article)
             redirect_back fallback_location: @article, notice: "Unfavorited #{@article.title}"
             
             
        else
             redirect_back fallback_location: root_path, notice: "Nothing happened"
             
        end
     end
    
end

private
    def article_params
        params.require(:article).permit(:title, :text, :search, :favorite)
    end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<h2>Favorite Articles</h2>
<% begin %>
<% if current_user.name != "" %>
<% current_user.favorites.each do |article| %>
<p>
  <!--%= article.label :type %-->
  <%= link_to article.title, article_path(article) %>
</p>
<% end %>
<% end %>
<% rescue %>
<% end %>

<p>
  Sort by:
  <%= link_to "Newest", articles_path(order: 'created_at DESC') %>
  <%= link_to "Oldest", articles_path(order: 'created_at ASC') %>
  <%= link_to "Title", articles_path(order: 'title') %>
</p>

<table>
  <% @articles.each do |article| %>
    <tr>
      <% begin %>
      <% if current_user.name != "" %>
      <td style="text-align:center">
        <p class = "rating">
          <%= article.likes.count - article.dislikes.count %>
        </p>
        <%= button_to '∧', article_likes_path(article), method: :article %>
        <%= button_to '∨', article_dislikes_path(article), method: :article %>
      </td>
      <% end %>
      <% rescue %>
      <% end %>
      <td>
        Posted by:
        <% if article.user %>
            <!--display authors name if there is one-->
            <%= article.user.name %>
            <% else %>
            [deleted]
          <% end %>
           at 
           <!--Timestamp for the creation of the article-->
      <%= article.created_at.change(offset: "+04:00").to_s(:db)%>
      <br>
      <p class = "Title">
      <%= article.title %>
      </p> 
      <%= link_to 'Show', article_path(article) %>
      <% begin %>
      <% if current_user == article.user || current_user.name == "Admin" %>
      <%= link_to 'Edit', edit_article_path(article) %>
      <%= link_to 'Delete', 
                                article_path(article),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %>
      <% end %>
      <% if current_user %>
      <%= link_to "Favorite", favorite_article_path(article, type: "favorite"), method: :put %>
      <%= link_to "Unfavorite", favorite_article_path(article, type: "unfavorite"), method: :put%>
      <% end %>
      <% rescue %>
      <% end %>
      <br>
      <div class = "Text">
      <%= article.text %>
      </div>
    </tr>
  <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<h1>
    <%= @article.title %>
</h1>
<p>
    <% begin %>
    <%= "Created by: " + @article.user.name + " at " + @article.created_at.change(offset: "+04:00").to_s(:db)%>
    <% rescue %>
    <%= "Created by: [deleted] at " + @article.created_at.change(offset: "+04:00").to_s(:db)%>
    <% end %>
</p>
<p>
    <%= simple_format(@article.text) %>
</p>

<p>
    <% begin %>
    <% if current_user.name != "" %>
    <%= link_to '∧', article_likes_path(@article), method: :article %>
    <%= @article.likes.count - @article.dislikes.count %>
    <%= link_to '∨', article_dislikes_path(@article), method: :article %>
    <% end %>
    <% rescue %>
    <% end %>
    <% begin %>
    <% if current_user == @article.user || current_user.name == "Admin" %>
    <%= link_to 'Edit', edit_article_path(@article) %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% rescue %>
    <% end %>
</p>
<br>
    <h3>-----------------------------------------</h3>
    <br>
<%= render @article.comments %>
<% begin %>
<% if current_user.name != "" %>
<h2>Add a comment:</h2>
<!--Form for the comments is at app/views/comments/_form.html.erb
    Rails understands comments/form-->
<%= render 'comments/form' %>
<br>
<% end %>
<% rescue %>
<% end %>
<%= link_to 'Article List', articles_path %>