blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'welcome/index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :articles do
    put :favorite, on: :member
   
  end
  
  resources :articles do  #create a route for the comments model
    resources :comments
    resources :likes
    resources :dislikes
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="hotbar">
      <div id= "logo">
        <%=link_to image_tag("logo.png"), controller: 'articles'%>
      </div>
      <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
      <%= submit_tag "Search" %>
      <% end %>
      <div id="new">
        <% begin %>
        <% if current_user.name != "" %>
        <%= link_to '🖉', new_article_path %>
        <% end %>
        <% rescue %>
        <% end %>
      </div>
      <div id="user">
        <% begin %>
        <%= link_to current_user.name, root_url %>
        <% rescue %>
        <%= link_to "Login", root_url %>
        <% end %>
      </div>
      <% begin %>
      <% if current_user.name == "Admin"%>
      <%= link_to 'Back', users_path %>
      <% end %>
      <% rescue %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>